### ISSUE TITLE
Make ml-tm-utils-pub into a cli for looking-glass

### ISSUE THREAD

**Issue by geohacker** [hotosm/ml-enabler#13]
After #4, we want to turn https://github.com/developmentseed/ml-tm-utils-pub/tree/master/ml_tm_utils_pub into a CLI so posting results to ml-enabler is easy.

**Comment by geohacker** [comment]
Fleshing this out a bit more. 

What we have so far:
* Dockerized looking-glass model, that takes images and produces building area predictions

The looking-glass CLI will have these utilities:
1. Convert model predictions to tile level json object
2. Find building area for a bbox at tile level from OSM using osm-task-metrics, and calculate the difference

The ml-enabler CLI will have the following utilities:
1. Post tile level JSON results to ml-enabler for a give model id


cc @batpad @wronk @xamanu

**Comment by batpad** [comment]
@wronk question: does it make sense to try and paralellize queries to the model docker container, or just send requests one at a time?

**Comment by wronk** [comment]
@batpad, I think we should try to parallelize it if possible. Drew did that in [chip 'n scale](https://github.com/developmentseed/chip-n-scale-queue-arranger) because the prediction involves multiple steps: getting tile index, fetching the tile image, packaging the image into a request, sending request/catching response, and some post-processing. If you can parallelize, we'll waste less of to docker images compute time (especially if we run it on a GPU).

**Comment by wronk** [comment]
@geohacker, the API looks good. Only thing to add is a simple post-processing script for the looking glass predictions. I'll create an issue about that.

**Comment by geohacker** [comment]
This done at https://github.com/hotosm/ml-enabler-cli/
