### ISSUE TITLE
Index predictions by quadkey, and store predictions per row

### ISSUE THREAD

**Issue by geohacker** [hotosm/ml-enabler#23]
I've been making good progress on fetching predictions #21, and came across a few caveats of the current db schema and API design. Since it's still early stages, we have a few ways forward - they will involve some schema changes, and adjustments in the expectation of the API response. 

**Problem**: looking-glass for example, predicts at z18. We want to store this in the ml-enabler database which is no problem at all. But when querying we will have to go from a bbox (from the request) to z18 tile indices like this: https://github.com/hotosm/ml-enabler/blob/3ae2c67eafd951e21c57e786d2fbd40d66476e8d/ml_enabler/services/prediction_service.py#L47-L50

Now to pick these keys from the database, we'll have serialize these tile indices to pass via SQLAlchemy and this will likely fail because of the number of tiles. It will also get challenging to aggregate the values in Python after the query is complete, if at all.

A fundamental thing to note is that this is likely also difficult for the clients to receive z18 tiles or whatever the most granular model output is. 

Instead, @batpad and I talked about the following approach:
1. Store individual predictions into a different table with a schema like `prediction_id integer, quadkey string, predictions JSONB`
2. From the client, receive a bbox as well as a tile size / quadkey size. For example, TM could request for predictions for a bbox of a neighborhood at tile size of z16.
3. We'll query for all the predictions that fall in this quadkey, using basic string [pattern matching](https://docs.microsoft.com/en-us/bingmaps/articles/bing-maps-tile-system) which is indexed. This allows for a faster query of all predictions within the bbox. 
4. If we store the predictions per row, aggregation also becomes an easier task to write than cumbersome queries in JSON.
5. Note that the predicted key value pairs will remain as a JSONB. So we can be flexible as to what any model wants to store. 

Few considerations:
1. When the prediction is at z18, clients cannot request for a tile size of z18 - this would ruin the point of implementing a hash index
2. The tile size can remain flexible and allow models and clients to chose what they think is best. The bigger the tile size in area is, the faster queries.

cc @batpad @xamanu @wronk

**Comment by batpad** [comment]
Just to add some notes here:

I think the big realization here is that the zoom levels the models predict things at will not be the same granularity that it would make sense for clients to fetch data at. Most often, if the tiles are stored at `z18`, we would want to query them aggregated at a lower zoom level like`z15` - practically, `z18` is too many tiles to send down to the client. Also, different models would want to store things at zoom levels and clients will probably need them at varying aggregations (lower zoom levels for large task areas, etc.)

Also, for performance reasons, we want to perform these aggregations in the database rather than picking out values for all `z18` tiles from the database and then aggregating in python code. So, to roughly outline what this process would look like:

 - Client sends a request for a bounding box, and zoom level they want results aggregated at.
 - We find all tiles of the requested zoom level that intersect with the bounding box.
 - So for eg. we get a bounding box and want aggregates of 100 z15 tiles - we would need to write a query that groups the `z18` tiles by these `z15` quadkeys: i.e. find and aggregate all `z18` tiles within these `z15` quadkeys and return values aggregated to the `z15` quadkeys.

I can see this query being relatively straightforward with having a separate table for `TilePrediction` or so as you describe above @geohacker. We will just need a slightly fancy string index on the `quadkey` column to optimize for "starts with" type queries and the grouping and aggregation should be straightforward.

Of course, moving to this model, we will no longer be able to write the big blob of JSON for a Prediction in a single database operation, but would need to insert rows individually. My recommendation here would be to have an end-point to add a single tile prediction, and let clients figure out batching requests / add this functionality to the CLI tool.

The other option would be to see if we are able to optimize the query to group and aggregate by quadkeys using the same JSON structure. Looking at the JSONB postgres documentation, it didn't seem super clear how one aggregates between multiple keys of the same row (with specifying a conditional filter for which keys to use in the aggregation) - if someone has a good idea on implementing this with the existing JSONB field, that could work as well.

A third option would be to just not do aggregations -- just settle on a single zoom level and force all models to write predictions at the same level and clients to query at the same zoom level. For `looking-glass` for eg., we could pre-process the model outputs and aggregate up to say `z15`. This does seem a bit inflexible though, and it definitely seems nicer to store the data at higher granularities.

This is an interesting one to solve :-) - the potentially large amounts of tiles / rows of data involved here necessitates worrying a bit about how we index and efficiently query - I think this solution of a separate table with appropriate indexes works, but it does have its trade-offs - would be great to hear feedback and other ideas.

**Comment by geohacker** [comment]
Taking this idea forward, we're going to make some db schema changes:

* Create a `prediction_tiles` table with an FK to `predictions` and columns `id integer, quadkey string, centroid geometry, predictions JSONB`
* Storing the centroid of the tile as a geometry will make task level API calls much faster and can aggregate accurately 
* The predictions will still remain as a JSONB column to allow models to be flexible
* Quadkey can be any size and doesn't limit models from posting any tile size predictions.

**Comment by geohacker** [comment]
This is done in #21.
